### ISSUE TITLE
how to import to my class

### ISSUE THREAD

**Issue by robellebor** [arenn/java-getopt#11]
i have added the .jar file to my library,  but i cant figure out how to import it to my class

**Comment by floscher** [comment]
The answer to your question is:
```java
import gnu.getopt.Getopt;
```
But that's probably not what you want to know :wink:.

To me it sounds more like you are struggling to add the *.jar to the classpath. Maybe you can describe in more detail what you mean by
> added the .jar file to my library

Where did you put it? What build system do you use if any? How do you put the *.jar file on the compile classpath (let the build system do that or some other way).

**Comment by robellebor** [comment]
ya i have tried that , and it says "package gnu.getopt does not exist"

and i added the .jar to my library
![picforstack](https://user-images.githubusercontent.com/25474834/34599585-0353e20c-f1a8-11e7-8621-a3a67a25a83d.png)

**Comment by floscher** [comment]
You have it "in your libraries" as a `*.jar.zip` file instead of a `*.jar` file.

Remove the zip files of getopt and instead add `java-getopt-1.0.14.jar` from the following link: https://github.com/floscher/java-getopt/releases/tag/v1.0.14

Then it should work.

**Comment by robellebor** [comment]
thanks it worked.
