### ISSUE TITLE
Switch license to current LGPLv3?

### ISSUE THREAD

**Issue by floscher** [arenn/java-getopt#8]
Currently the source code is under the GNU Library General Public License, which [has been superseded by the GNU Lesser General Public License](https://www.gnu.org/licenses/old-licenses/lgpl-2.0.en.html).

@arenn would it be ok for you, if the license would be updated to the [LGPLv3](https://www.gnu.org/licenses/lgpl-3.0.en.html), at least for the changes that I've made and those that I will make in [my fork of your repository](https://github.com/floscher/java-getopt).

**Comment by arenn** [comment]
As far as I'm concerned, go ahead. I believe these licenses generally
specify that you can use "any later version" of the GNU license in
question. I will say that since I adapted it from the code in the GNU C
Library, I don't own the underlying, original copyright and thus can't
speak for the FSF. I will look at this further in the future. Thanks, Aaron.

On Fri, May 22, 2015 at 11:03 AM, Florian Schäfer notifications@github.com
wrote:

> Currently the source code is under the GNU Library General Public License,
> which has been superseded by the GNU Lesser General Public License
> https://www.gnu.org/licenses/old-licenses/lgpl-2.0.en.html.
> 
> @arenn https://github.com/arenn would it be ok for you, if the license
> would be updated to the LGPLv3
> https://www.gnu.org/licenses/lgpl-3.0.en.html, at least for the changes
> that I've made and those that I will make in my fork of your repository
> https://github.com/floscher/java-getopt.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arenn/java-getopt/issues/8.

## 

Aaron M. Renn
arenn@urbanophile.com | www.urbanophile.com | twitter.com/urbanophile

**Comment by floscher** [comment]
Thank you for answering so unbelievably fast ;).
I've now changed the license [at least for my master-branch](https://github.com/floscher/java-getopt/tree/master). If you want, I could also open a pull request against your master branch containing the new license.

**Comment by arenn** [comment]
You could do that, but I haven't really mastered github yet. I've only been
using it as an internet backup for my personal repositories. I spent too
much time back in the day using CVS and have never really fully figured out
the world's shift to git. Cheers, Aaron.

On Fri, May 22, 2015 at 11:32 AM, Florian Schäfer notifications@github.com
wrote:

> Thank you for answering so unbelievably fast ;).
> I've now changed the license at least for my master-branch
> https://github.com/floscher/java-getopt/tree/master. If you want, I
> could also open a pull request against your master branch containing the
> new license.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arenn/java-getopt/issues/8#issuecomment-104692211.

## 

Aaron M. Renn
arenn@urbanophile.com | www.urbanophile.com | twitter.com/urbanophile
